//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllergyUser
    {
        public int AllergyID { get; set; }
        public int UserID { get; set; }
        public string Precautions { get; set; }
    
        public virtual Allergy Allergy { get; set; }
        public virtual AppUser AppUser { get; set; }
    }
}
