//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Disaster()
        {
            this.HelpUsers = new HashSet<HelpUser>();
            this.DisasterUsers = new HashSet<DisasterUser>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> DisasterDate { get; set; }
        public Nullable<int> DamageLevel { get; set; }
        public Nullable<int> Casualties { get; set; }
        public Nullable<int> DisasterID { get; set; }
        public Nullable<int> CityID { get; set; }
    
        public virtual City City { get; set; }
        public virtual DisasterType DisasterType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HelpUser> HelpUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisasterUser> DisasterUsers { get; set; }
    }
}
