//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Allergy> Allergies { get; set; }
        public virtual DbSet<AllergyUser> AllergyUsers { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Disability> Disabilities { get; set; }
        public virtual DbSet<DisabilityUser> DisabilityUsers { get; set; }
        public virtual DbSet<Disaster> Disasters { get; set; }
        public virtual DbSet<DisasterType> DisasterTypes { get; set; }
        public virtual DbSet<DisasterUser> DisasterUsers { get; set; }
        public virtual DbSet<EmergencyContact> EmergencyContacts { get; set; }
        public virtual DbSet<EmergencyContactUser> EmergencyContactUsers { get; set; }
        public virtual DbSet<EmergencyService> EmergencyServices { get; set; }
        public virtual DbSet<Help> Helps { get; set; }
        public virtual DbSet<HelpUser> HelpUsers { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<SafeLocation> SafeLocations { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UserSkill> UserSkills { get; set; }
    }
}
