//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSkill
    {
        public int SkillID { get; set; }
        public int UserID { get; set; }
        public string ExperienceLevel { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
